export const data = [
    {
      id: 1,
      key: "1",
      orderId: "#254841",
      customer: "Dianne Russell",
      type: "Student",
      date: "25 Jan 2022",
      status: "Received",
      commission: "95.00",
    },
    {
      id: 2,
      key: "2",
      orderId: "#254841",
      customer: "Bessie Cooper",
      type: "Teacher",
      date: "25 Jan 2022",
      status: "Pending",
      commission: "95.00",
    },
    {
      id: 3,
      key: "3",
      orderId: "#254841",
      customer: "Cameron Williamson",
      type: "Student",
      date: "25 Jan 2022",
      status: "Received",
      commission: "95.00",
    },
    {
      id: 4,
      key: "4",
      orderId: "#254841",
      customer: "Kathryn Murphy",
      type: "Teacher",
      date: "25 Jan 2022",
      status: "Received",
      commission: "95.00",
    },
    {
      id: 5,
      key: "5",
      orderId: "#254841",
      customer: "Theresa Webb",
      type: "Teacher",
      date: "25 Jan 2022",
      status: "Received",
      commission: "95.00",
    },
    {
      id: 6,
      key: "6",
      orderId: "#254841",
      customer: "Guy Hawkins",
      type: "Student",
      date: "25 Jan 2022",
      status: "Received",
      commission: "95.00",
    },
    {
      id: 6,
      key: "7",
      orderId: "#254841",
      customer: "Cody Fisher",
      type: "Student",
      date: "25 Jan 2022",
      status: "Received",
      commission: "95.00",
    },
    {
      id: 8,
      key: "8",
      orderId: "#254841",
      customer: "Savannah Nguyen",
      type: "Student",
      date: "25 Jan 2022",
      status: "Pending",
      commission: "95.00",
    },
    {
      id: 9,
      key: "9",
      orderId: "#254841",
      customer: "Leslie Alexander",
      type: "Student",
      date: "25 Jan 2022",
      status: "Received",
      commission: "95.00",
    },
    {
      id: 10,
      key: "10",
      orderId: "#254841",
      customer: "Floyd Miles",
      type: "Teacher",
      date: "25 Jan 2022",
      status: "Received",
      commission: "95.00",
    },
    {
      id: 11,
      key: "11",
      orderId: "#254841",
      customer: "Courtney Henry",
      type: "Student",
      date: "25 Jan 2022",
      status: "Received",
      commission: "95.00",
    },
  ];
